/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sportvill.test;

import br.com.sportvill.dominio.Cadastro;
import br.com.sportvill.test.DataBaseTest;
import br.com.sportvill.test.CadastroBusinessMock;


/**
 *
 * @author kevin
 */
public class TelaCadastroTest extends javax.swing.JFrame {

    
    Cadastro cad = new Cadastro();
    CadastroBusinessMock control = new CadastroBusinessMock();
    DataBaseTest conectarBD = new DataBaseTest();
    
    /**
     * Creates new form TelaCadastroTest
     */
    public TelaCadastroTest() {
        initComponents();
        
        //Ao fazer isso, estará chamando todas as instruções da DataBaseTest
        conectarBD.conexao();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cadastro = new javax.swing.JLabel();
        Usuário = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        CampoEspaçoNome = new javax.swing.JTextField();
        CampoEspaçoSenha = new javax.swing.JPasswordField();
        CriarConta = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        IrParaTelaDeLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cadastro.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        Cadastro.setText("Cadastro");

        Usuário.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Usuário.setText("Usuário:");

        Senha.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Senha.setText("Senha:");

        CriarConta.setBackground(java.awt.Color.white);
        CriarConta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        CriarConta.setForeground(java.awt.Color.red);
        CriarConta.setText("Criar Conta");
        CriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarContaActionPerformed(evt);
            }
        });

        BotaoSair.setBackground(java.awt.Color.white);
        BotaoSair.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BotaoSair.setForeground(java.awt.Color.red);
        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        IrParaTelaDeLogin.setBackground(java.awt.Color.white);
        IrParaTelaDeLogin.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        IrParaTelaDeLogin.setForeground(java.awt.Color.red);
        IrParaTelaDeLogin.setText("Clique aqui para ir para a tela de Login");
        IrParaTelaDeLogin.setBorderPainted(false);
        IrParaTelaDeLogin.setContentAreaFilled(false);
        IrParaTelaDeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrParaTelaDeLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CriarConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoSair)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Senha)
                            .addComponent(Usuário))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoEspaçoSenha)
                            .addComponent(CampoEspaçoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(IrParaTelaDeLogin)))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Cadastro)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuário)
                    .addComponent(CampoEspaçoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Senha)
                    .addComponent(CampoEspaçoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IrParaTelaDeLogin)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarConta)
                    .addComponent(BotaoSair))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(511, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
        conectarBD.desconectar();
        System.exit(0);
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void IrParaTelaDeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrParaTelaDeLoginActionPerformed
        // TODO add your handling code here:
        
        TelaLoginTest ChamarTelaLogin = new TelaLoginTest();
        
    //Chama a outra Jframe
        ChamarTelaLogin.setVisible(true); 
        
    //Encerra a Jframe anterior
        dispose();
        
    }//GEN-LAST:event_IrParaTelaDeLoginActionPerformed

    private void CriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarContaActionPerformed
        // TODO add your handling code here:
        cad.setNome(CampoEspaçoNome.getText());        
        cad.setSenha(CampoEspaçoSenha.getText());
        control.Salvar(cad);
        
        
    }//GEN-LAST:event_CriarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSair;
    private javax.swing.JLabel Cadastro;
    private javax.swing.JTextField CampoEspaçoNome;
    private javax.swing.JPasswordField CampoEspaçoSenha;
    private javax.swing.JButton CriarConta;
    private javax.swing.JButton IrParaTelaDeLogin;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Usuário;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
